version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fms-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: fms_db
    ports:
      - '5432:5432'
    volumes:
      - fms-db-data:/var/lib/postgresql/data

volumes:
  fms-db-data:
